spring.application.name=moviebooking

spring.datasource.url=jdbc:postgresql://localhost:5432/ces
spring.datasource.username=reaganpastor
spring.datasource.password=OrAmIJustCoping?27

spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=true
