spring.application.name=moviebooking

spring.datasource.url=jdbc:postgresql://localhost:5432/ces
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=true

spring.mail.host=smtp.sendgrid.net
spring.mail.port=587
spring.mail.username=apikey
spring.mail.password=Your_SendGrid_API_Key_Here
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=reaganelizabeth@gmail.com
